#!/usr/bin/env ruby

require 'taxes'
require 'optparse'

options = {}

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: taxes [options]'

  opts.on(
    '-b BRACKETS',
    '--brackets BRACKETS',
    'JSON files containing with the tax brackets') do |brackets|
    options[:brackets] = brackets
  end

  opts.on(
    '-i INCOMES',
    '--incomes INCOMES',
    'Plain text file, one income per line') do |incomes|
    options[:incomes] = incomes
  end

  opts.on(
    '-o FILENAME',
    '--output FILENAME',
    'File to write the tax amount due for each income to') do |output|
    options[:output] = output
  end
end
parser.parse!

# Display usage if missing any of the arguments
required = %i[brackets incomes output]
unless required.all? { |name| options[name] }
  puts parser
  exit 1
end

# Load the brackets and incomes
brackets = Taxes::Datasource.load_tax_brackets(options[:brackets])
incomes  = Taxes::Datasource.load_incomes(options[:incomes])

# Create a tax engine
engine = Taxes::Engine.new(brackets: brackets)

# Gather taxes due
income_taxes = incomes.each { |income| engine.taxes_due(income) }

# Write to the output
File.open(options[:output], 'w+') do |file|
  income_taxes.each { |income_tax| file.puts(income_tax) }
end
